name: MoneyRanking
main: cn.lanink.moneyranking.MoneyRanking
version: "1.2.1"
api: ["1.0.0"]
load: POSTWORLD
author: "LT_Name"
depend:
  - "RankingAPI"
softdepend:
  - "playerPoints"
  - "EconomyAPI"
  - "Money"
  - "LlamaEconomy"

commands:
  moneyranking:
    description: "§aMoneyRanking command"
    usage: "§a/moneyranking 打开GUI界面"
    permission: moneyranking.admin

permissions:
  moneyranking.admin:
    default: op